# Generated by Django 2.2.3 on 2019-07-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangotask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemworkflow',
            name='raters_actual',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='itemworkflow',
            name='raters_desired',
            field=models.PositiveIntegerField(),
        ),
    ]
