# Generated by Django 2.2.4 on 2019-08-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='evidence_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rater_answer_judgment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rater_answer_predict_a',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rater_answer_predict_b',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rater_answer_predict_c',
            field=models.TextField(null=True),
        ),
    ]
