# Generated by Django 2.2.4 on 2019-08-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_auto_20190822_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='evidence_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rater_answer_judgment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rater_answer_predict_a',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rater_answer_predict_b',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rater_answer_predict_c',
            field=models.TextField(blank=True, null=True),
        ),
    ]
