# Generated by Django 2.2.4 on 2019-08-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20190826_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='rater',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rater',
            name='api_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
