# Generated by Django 2.2.4 on 2019-08-28 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20190828_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rater',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
