# Generated by Django 2.2.4 on 2019-09-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_auto_20190903_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rater_answer_evidence',
            field=models.TextField(blank=True, null=True),
        ),
    ]
