# Generated by Django 2.2.4 on 2019-09-10 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_answer_rater_answer_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Item'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='rater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Rater'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Workflow'),
        ),
        migrations.AlterField(
            model_name='rater',
            name='workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Workflow'),
        ),
    ]
