# Generated by Django 2.2.4 on 2019-09-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_auto_20190910_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='api_id',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
