# Generated by Django 2.2.4 on 2019-09-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_item_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
