# Generated by Django 2.2.4 on 2019-09-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0015_auto_20190917_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='judgment_additional_information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
