# Generated by Django 2.2.4 on 2019-09-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0016_answer_judgment_additional_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='judgment_additional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
