# Generated by Django 2.2.4 on 2019-10-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0017_workflow_judgment_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='rater',
            name='assignment_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rater',
            name='hit_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rater',
            name='worker_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rater',
            name='worker_state',
            field=models.CharField(blank=True, choices=[('rejected', 'rejected'), ('accepted', 'accepted')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rater',
            name='age',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rater',
            name='api_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rater',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rater',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rater',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
