# Generated by Django 2.2.4 on 2019-10-03 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0018_auto_20191003_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rater',
            name='assignment_id',
        ),
        migrations.RemoveField(
            model_name='rater',
            name='hit_id',
        ),
        migrations.RemoveField(
            model_name='rater',
            name='worker_state',
        ),
        migrations.AddField(
            model_name='rater',
            name='completed_demographics_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rater',
            name='completed_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rater',
            name='completed_register_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rater',
            name='rejected_state',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=255, unique=True)),
                ('hit_id', models.CharField(max_length=255)),
                ('rater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.Rater')),
            ],
        ),
    ]
