# Generated by Django 2.2.4 on 2019-10-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0020_assignment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rater_answer_judgment_inform',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='rater_answer_judgment_reduce',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='rater_answer_judgment_remove',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='judgment_inform',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='judgment_reduce',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='judgment_remove',
            field=models.TextField(blank=True, null=True),
        ),
    ]
